stampapp/config/routes.rb
Stampapp::Application.routes.draw do
  resources :stamps
  root to: 'stamps#index'
end

stampapp/app/models/stamp.rb
class Stamp < ActiveRecord::Base
  attr_accessible :image
  mount_uploader :image, StampUploader
end

stampapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

stampapp/app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  # GET /stamps
  # GET /stamps.json
  def index
    @stamps = Stamp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stamps }
    end
  end

  # GET /stamps/1
  # GET /stamps/1.json
  def show
    @stamp = Stamp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stamp }
    end
  end

  # GET /stamps/new
  # GET /stamps/new.json
  def new
    @stamp = Stamp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stamp }
    end
  end

  # GET /stamps/1/edit
  def edit
    @stamp = Stamp.find(params[:id])
  end

  # POST /stamps
  # POST /stamps.json
  def create
    @stamp = Stamp.new(params[:stamp])

    respond_to do |format|
      if @stamp.save
        format.html { redirect_to @stamp, notice: 'Stamp was successfully created.' }
        format.json { render json: @stamp, status: :created, location: @stamp }
      else
        format.html { render action: "new" }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stamps/1
  # PUT /stamps/1.json
  def update
    @stamp = Stamp.find(params[:id])

    respond_to do |format|
      if @stamp.update_attributes(params[:stamp])
        format.html { redirect_to @stamp, notice: 'Stamp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stamps/1
  # DELETE /stamps/1.json
  def destroy
    @stamp = Stamp.find(params[:id])
    @stamp.destroy

    respond_to do |format|
      format.html { redirect_to stamps_url }
      format.json { head :no_content }
    end
  end
end

stampapp/app/helpers/application_helper.rb
module ApplicationHelper
end

stampapp/app/helpers/stamps_helper.rb
module StampsHelper
end

stampapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

stampapp/app/views/stamps/_form.html.erb
<%= form_for @stamp do |f| %>
  <% if @stamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stamp.errors.count, "error") %> prohibited this stamp from being saved:</h2>
      <ul>
      <% @stamp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image, "Upload Image" %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

stampapp/app/views/stamps/edit.html.erb
<h1>Editing stamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @stamp %> |
<%= link_to 'Back', stamps_path %>

stampapp/app/views/stamps/index.html.erb
<h1>Stamps</h1>

<% @stamps.each do |stamp| %>
  <div class="stamp">
    <%= image_tag stamp.image_url(:blue) %>
  </div>
<% end %>
<div class="clear"></div>

<p><%= link_to "New Stamp", new_stamp_path %></p>

stampapp/app/views/stamps/new.html.erb
<h1>New stamp</h1>

<%= render 'form' %>

<%= link_to 'Back', stamps_path %>

stampapp/app/views/stamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @stamp.image %>
</p>


<%= link_to 'Edit', edit_stamp_path(@stamp) %> |
<%= link_to 'Back', stamps_path %>